export enum ErrorsEnum {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_INPUT_ERROR = 'BAD_INPUT_ERROR',
  FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_EMAIL_ADDRESS = 'INVALID_EMAIL_ADDRESS',
  WRONG_PASSWORD = 'WRONG_PASSWORD',
  EMAIL_ALREADY_EXISTS = 'EMAIL_EXISTS',
  EMPTY_BODY_ERROR = 'EMPTY_BODY_ERROR',
  USER_NOT_EXISTS = 'USER_NOT_EXISTS',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}